version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_DB: ping_prog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  migrations:
    #build: .   #для запуска из проекта
    image: artizzzz/ping_prog:latest
    container_name: goose_migrations
    depends_on:
      - postgres
    command: >
      goose -dir ./db/migrations
      postgres "host=postgres port=5432 user=postgres password=123 dbname=ping_prog sslmode=disable"
      up
    restart: "no"

  app:
    #build: .   #для запуска из проекта
    image: artizzzz/ping_prog:latest
    container_name: myapp
    depends_on:
      - postgres
      - migrations
    #env_file:
    #  - cmd/.env
    # без проекта убрать env_file и указать напрямую бот токен
    environment:
      DATABASE_URL: "postgres://postgres:123@postgres:5432/ping_prog?sslmode=disable"
      #TokenTelegramBot: "63673......"    #!!!!!!!!!!!!!!!!!!!
    restart: always

volumes:
  pgdata:
